### PR TITLE
Fix baseline resolver

### LINKED ISSUE #612: Issue with BASELINE RESOLVER - 3.0.11-beta version
### Basic information

* My operating system: Windows 10
* My MZmine version: 3.0.11-beta

### What happened
Dear developers,
I am trying to reproduce a job I already performed on the old version MZmine 2.53, I started from Thermo raw data and I adopted the same parameters for mass detection and ADAP chromatogram builder, when it came to the deconvolution I tried to use the "baseline resolver" algorithm which I think is the equivalent of "baseline cut-off" in the 2.53 version, in fact, I put the same parameters, but this time I got this error for each feature list.

error ResolvedPeak java 105

Could you give an explanation for this?

Parameters
-mass detention: MS1 noise level: 10000, MS2 noise level 100
-ADAP chrom builder: Scans MSlevel 1, Min group size n of scans: 3, group intensity: 10000, min intensity:10000, scan accuracy 20 ppm
-Baseline resolver: MS/MS scan pairing (RT toll:0.3, MS1MS2 toll: 5ppm), Min peak height: 10000, peak duration 0-2 min, Baseline level:10000 ---  ERROR ---

Thank you in advance,
Giovanni

### PR DESCRIPTION
**Pull request by SteffenHeu**
Assertion was triggered when there was only one data point in the resolved feature. Don't know how it was handled in MZmine 2, the assertion was there sicne 2010 (accordingto git blame)

Also fixed FeatureConvertors#ResolvedPeakToMoularFeature

Edit: fixes #612

### CODE REVIEW

File: src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/baseline/BaselineFeatureResolver.java [hunk 1]
```diff
@@ -110,7 +110,7 @@
         currentRegionEnd--;
 
         // Check current region, if it makes a good peak.
-        if (durationRange
+        if (currentRegionEnd - currentRegionStart > 0 && durationRange
```
Comment (robinschmid) [inline src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/baseline/BaselineFeatureResolver.java:113]: so you basically added a minimum number of data points of 2 here

**Review by robinschmid — APPROVED** [review]
looks good to me. Only thing might be to introduce a minimum number of data points parameter (like we did for local min) instead of forcing 2 datapoints

File: src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/baseline/BaselineFeatureResolver.java (hunk 1 above)
Comment (SteffenHeu) [reply src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/baseline/BaselineFeatureResolver.java:113]: Yes

Comment (SteffenHeu) [reply src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/baseline/BaselineFeatureResolver.java:113]: But looking at the history of resolved peak, the assertion was there since 2010. So it must not have been triggered before.

File: src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/FeatureResolverTask.java [hunk 2]
```diff
@@ -434,7 +434,11 @@ private FeatureList resolvePeaks(final ModularFeatureList originalFeatureList,
       final ResolvedPeak[] peaks = resolver.resolvePeaks(originalFeature, parameters, rSession,
           mzCenterFunction, msmsRange, RTRangeMSMS);
 
+      final Integer minNumDp = parameters.getValue(GeneralResolverParameters.MIN_NUMBER_OF_DATAPOINTS);
```
Comment (robinschmid) [inline src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/FeatureResolverTask.java:437]: Can you move this outside of the rows loop?
parameter.getValue is not really effective.

File: src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/baseline/BaselineFeatureResolver.java (hunk 1 above)
Comment (robinschmid) [inline src/main/java/io/github/mzmine/modules/dataprocessing/featdet_chromatogramdeconvolution/baseline/BaselineFeatureResolver.java:113]: this check can now be removed. currentRegionEnd is always >= start. ResolvedPeak is now also allowing 1 dp
