### PR TITLE
Grid mass fix

### LINKED ISSUE #838: ArrayIndexOutOfBounds Exception in Grid Mass module
### Basic information

* My operating system: Windows 10 Pro
* My MZmine version: MZmine 3.1.26-beta

### What happened

image

### PR DESCRIPTION
**Pull request by omokshyna**
Added an error message for when the MS level > 1 is chosen.
Cleared a bit the code - deleted unused variables and methods, removed unused commented code, comments in Spanish, etc.
Several TODOs were added just in case one day this method will be rewritten.
Closes #838

### CODE REVIEW

File: src/main/java/io/github/mzmine/modules/dataprocessing/filter_groupms2/GroupMS2Parameters.java [hunk 1]
```diff
@@ -56,10 +56,7 @@ public class GroupMS2Parameters extends SimpleParameterSet {
 
   public static final BooleanParameter lockMS2ToFeatureMobilityRange = new BooleanParameter(
       "Lock to feature mobility range",
-      "If checked, only mobility scans from the mobility range of the feature will be merged.\n"
-          + "This is usually not needed. However, if isomeres/isobares elute at the same retention time and are close in mobility, "
-          + "the MS/MS window might be larger than the peak in mobility dimension and thus cause chimeric MS/MS spectra.\n"
-          + "This can be investigated in hte \"All MS MS\" window", false);
+      "If checked, only mobility scans from the mobility range of the feature will be merged.", false);
```
Comment (SteffenHeu) [inline src/main/java/io/github/mzmine/modules/dataprocessing/filter_groupms2/GroupMS2Parameters.java:59]: why did you remove the additional explaination?

File: src/main/java/io/github/mzmine/modules/dataprocessing/featdet_gridmass/GridMassParameters.java [hunk 2]
```diff
@@ -80,6 +81,19 @@ public class GridMassParameters extends SimpleParameterSet {
       "To avoid estimation of features at specific times in minutes. Use 0-0 to ignore. Format: time1-time2, time3-time4, ... ",
       "0-0");
 
+  @Override
+  public boolean checkParameterValues(Collection<String> errorMessages) {
+    boolean allParameterOK = super.checkParameterValues(errorMessages);
+
+    if (scanSelection.getValue().getMsLevel() > 1) {
```
Comment (SteffenHeu) [inline src/main/java/io/github/mzmine/modules/dataprocessing/featdet_gridmass/GridMassParameters.java:88]: since the msLevel is an Integer, this might lead  to an NPE when no msLevel is set in the dialog. I think we also need a  null check here. Null can lead to the same error message

Comment (omokshyna) [reply src/main/java/io/github/mzmine/modules/dataprocessing/featdet_gridmass/GridMassParameters.java]: You're right. Null check added
