### PR TITLE
fix exceptions in SameRangeTask and SimpleGapFeature

### LINKED ISSUE #648: Gap filling doesn't seems to work Java "OutOfBoundsException" error
### Basic information

* My operating system: Windows 10 Home Version 21H1
* My MZmine version: 3.0.21 beta
* My CPU: Intel Core i7-9700K
* RAM: 32 GB at 3200 MHz

### What happened
First I had problems with RANSAC alignment module. I uninstalled and install it again. When RANSAC it's completed, I tried to perform a GAP Filling but I always get this error message: 

"Unhandled exception in task Gap filling RANSAC using RT and m/z range: java.lang.IndexOutOfBoundsException (NativeConstructorAccessorImpl.java:-2)

And anything happens after that.

MMZmine parameters for Gap Filling:
Parameters

Error screenshot:
Error

Thank you in advance for your help and support.

### PR DESCRIPTION
**Pull request by SteffenHeu**
fixes #648 / #649

### CODE REVIEW

File: src/main/java/io/github/mzmine/modules/dataprocessing/gapfill_samerange/SameRangeTask.java [hunk 1]
```diff
@@ -91,17 +92,15 @@ public void run() {
...
     // Create new feature list
     processedPeakList = new ModularFeatureList(peakList + " " + suffix, getMemoryMapStorage(),
         columns);
 
-    processedRowsAtomic = new AtomicInteger(0);
-
     List<FeatureListRow> outputList = Collections.synchronizedList(new ArrayList<>());
 
-    peakList.parallelStream().map(r -> (ModularFeatureListRow) r).forEach(sourceRow -> {
+    peakList.stream().map(r -> (ModularFeatureListRow) r).forEach(sourceRow -> {
```
Comment (robinschmid) [inline src/main/java/io/github/mzmine/modules/dataprocessing/gapfill_samerange/SameRangeTask.java:103]: this is intended?
If that is needed for the fix we can merge it. otherwise it owuld be nice to keep parallel

**Comment by robinschmid** [comment]
Only one comment and its ready to be merged

File: src/main/java/io/github/mzmine/modules/dataprocessing/gapfill_samerange/SameRangeTask.java (hunk 1 above)
Comment (SteffenHeu) [reply src/main/java/io/github/mzmine/modules/dataprocessing/gapfill_samerange/SameRangeTask.java:103]: yes, this error otherwise:

```
2022-04-04 10:00:27 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Unhandled exception java.util.ConcurrentModificationException: java.util.ConcurrentModificationException while processing task Gap filling Aligned feature list using RT and m/z range
java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.mzmine.modules.dataprocessing.gapfill_samerange.SameRangeTask.run(SameRangeTask.java:101)
	at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)
```
